### ISSUE TITLE
Create a new tag

### ISSUE THREAD

**Issue by Tafkas** [fdellavedova/pycriteo#4]
There should be a new tag and release for PyPi.

**Comment by Tafkas** [comment]
@fdellavedova could you please create a new tag and release for PyPi.

**Comment by fdellavedova** [comment]
done. I added you to the contributors list, thanks for your help!

PyPi -> https://pypi.python.org/pypi?:action=display&name=pycriteo&version=0.0.2

**Comment by Tafkas** [comment]
Thank you.
